spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/gallery
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.default_batch_fetch_size: 1000
      hibernate:
        format_sql: true

  # redis
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

  output:
    ansi:
      enabled: always

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  live:
    # 7일
    rtk: 604800000

server:
  port: 8088
